swagger: '2.0'
info:
  title: ''
  description: ''
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
x-google-backend:
  address: ''
paths:
  /translate:
    post:
      summary: Translate text
      operationId: translateText
      security:
       - api_key: []
      responses:
        200:
          description: "OK"
          schema:
            type: string
        400:
          description: "Invalid"
          schema:
            type: string
  /hello:
    get:
      summary: Cloud Run hello world
      operationId: hello
      security:
       - api_key: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string
securityDefinitions:
    # This section configures basic authentication with an API key.
  api_key:
    type: apiKey
    name: key
    in: query